var whw_videos = [
  {
    "id": 3000,
    "email": "cheryl@csbryan.com",
    "job_title": "Executive & Leadership Coach",
    "company": "CS Bryan Executive Coaching & Team Development",
    "author": "Cheryl Smith Bryan",
    "category": "Compensation",
    "video_title": "Know Your Weak Spots",
    "tags": "improvement, weakness",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/CherylSmithBryan/CherylSmithBryan_Compensation_KnowYourWeakSpots-1464995243545.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/CherylSmith.PNG"
  },
  {
    "id": 3001,
    "email": "info@kforney.com",
    "job_title": "CEO & President",
    "company": "Forney Search",
    "author": "Kathie Forney",
    "category": "Compensation",
    "video_title": "Do Your Research Before Negotiating A Raise",
    "tags": "negotiation, communication, conversation, research",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/KathieForney/KathieForney_Compensation_DoYourResearchBeforeNegotiatingARaise-1464995338236.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/Kforney.PNG"
  },
  {
    "id": 3002,
    "email": "info@kforney.com",
    "job_title": "CEO & President",
    "company": "Forney Search",
    "author": "Kathie Forney",
    "category": "Compensation",
    "video_title": "Maximize Your Base Salary",
    "tags": "pay, finances, compensation",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/KathieForney/KathieForney_Compensation_MaximizeYourBaseSalary-1464995472300.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/Kforney.PNG"
  },
  {
    "id": 3003,
    "email": "info@kforney.com",
    "job_title": "CEO & President",
    "company": "Forney Search",
    "author": "Kathie Forney",
    "category": "Compensation",
    "video_title": "Never Give The First Number",
    "tags": "negotiation, communication, conversation",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/KathieForney/KathieForney_Compensation_NeverGiveTheFirstNumber-1464995602268.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/Kforney.PNG"
  },
  {
    "id": 3004,
    "email": "kimberly@cutchall.com",
    "job_title": "CEO & President",
    "company": "Accendo International",
    "author": "Kimberly Cutchall",
    "category": "Compensation",
    "video_title": "How to Get Paid More",
    "tags": "pay, finances, compensation, increase, raise",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/KimberlyCutchall/KimberlyCutchall_Compensation_HowToGetPaidMore-1464995765275.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/Kimberly.PNG"
  },
  {
    "id": 3005,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "Benchmark Against Men",
    "tags": "research, payment, money, finance",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/LeliaGowland/LeliaGowland_Compensation_BenchmarkAgainstMen-1464995817444.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3006,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "Broaden Your Definition",
    "tags": "negotiation, benefits, payment",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/LeliaGowland_Compensation_Broaden+Your+Definition.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3007,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "Don't Be Afraid of No",
    "tags": "negotiation, debate, conversation, finances",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/LeliaGowland/LeliaGowland_Compensation_DontBeAfraidOfNo-1464996141324.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3008,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "Manage Your Emotions",
    "tags": "negotiation, communication, conversation, emotions",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/LeliaGowland/LeliaGowland_Compensation_ManageYourEmotions-1464996226294.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3009,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "The Salary History Question",
    "tags": "history, salary, finances, payment",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/LeliaGowland/LeliaGowland_Compensation_TheSalaryHistoryQuestion-1464996388460.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3010,
    "email": "lgowland@gmail.com",
    "job_title": "Principal",
    "company": "Gowland LLC",
    "author": "Lelia Gowland",
    "category": "Compensation",
    "video_title": "When Your Collegues Make More Than You",
    "tags": "money, finance, competition, coworkers, negotiation",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/LeliaGowland/LeliaGowland_Compensation_WhenYourColleaguesMakeMoreThanYou-1464996475326.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/lgowland.PNG"
  },
  {
    "id": 3011,
    "email": "mvoorhees@becks.com",
    "job_title": "President",
    "company": "Becks Prime",
    "author": "Molly Voorhees",
    "category": "Compensation",
    "video_title": "Get Paid For What You Do",
    "tags": "money, finance, negotiation",
    "videofile_link": "https://d9z5ilwx89aa5.cloudfront.net/Compensation/Compensation/MollyVoorhees/MollyVoorhees_Compensation_GetPaidForWhatYouDo-1464996828339.mp4",
    "thumbnail_link": "https://s3.amazonaws.com/whw-thumbnails/Molly.PNG"
  }
]